apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: consul-dc1
  labels:
    app: consul
spec:
  serviceName: "consul"
  replicas: 5
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:1.19.1
        command: ["consul", "agent", "-config-file=/consul/config/consul.hcl"]
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
          protocol: UDP
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8300
          name: server
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-logs
          mountPath: /var/log
        - name: consul-config
          mountPath: /consul/config
      - name: promtail
        image: grafana/promtail
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
          - "-config.expand-env=true"
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail/
        - name: consul-logs
          mountPath: /var/log/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: consul-data
        emptyDir: {}
      - name: consul-logs
        emptyDir: {}
      - name: consul-config
        configMap:
          name: consul-server-config-dc1
      - name: promtail-config
        configMap:
          name: promtail-consul-config
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul-dc1
  labels:
    app: consul
spec:
  ports:
  - port: 8500
    name: http
  - port: 8600
    name: dns
    protocol: UDP
  - port: 8301
    name: serflan
  - port: 8302
    name: serfwan
  - port: 8300
    name: server
  clusterIP: None
  selector:
    app: consul