apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: consul-monitoring
  labels:
    name: loki-config
data:
  loki-local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: consul-monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki
        args:
        - "-config.file=/etc/loki/loki-local-config.yaml"
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config-volume
          mountPath: /etc/loki/
        - name: loki-storage-volume
          mountPath: /loki/
      volumes:
      - name: loki-config-volume
        configMap:
          name: loki-config
      - name: loki-storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: consul-monitoring
spec:
  selector:
    app: loki
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3100
